### ISSUE TITLE
Bug: 大写字母无效

### ISSUE THREAD

**Issue by iostyle** [rover95/morse-encrypt#1]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/22219146/62036506-861b1780-b224-11e9-857b-82d817891f48.png">

作者你好，有时间可否具体讲解一下转码和加密

**Comment by rover95** [comment]
密码字典是基于摩斯电码的，摩斯电码不区分大小写，所以没有支持大写字母，只支持小写和中文

**Comment by rover95** [comment]
原理其实很简单： 明文--> 摩斯电码 --> 零宽字符，定义好密码字典直接转换
