### ISSUE TITLE
解密后的文本丢了字符L和z

### ISSUE THREAD

**Issue by LeslieZhu** [rover95/morse-encrypt#6]
在：http://morse.rovelast.com/

比如：前后文本都不设置，只填入加密文本: `作者是LeslieZhu`，点击加密，得到加密文本:

```
&#8204;&#8205;&#8205;&#8204;&#8205;&#8203;&#8204;&#8204;&#8205;&#8203;&#8204;&#8204;&#8204;&#8204;&#8205;&#8203;&#8204;&#8204;&#8205;&#8204;&#8203;&#8204;&#8204;&#8204;&#8204;&#8204;&#8203;&#8205;&#8204;&#8205;&#8204;&#8203;&#8204;&#8205;&#8205;&#8204;&#8205;&#8203;&#8204;&#8204;&#8205;&#8203;&#8205;&#8205;&#8205;&#8204;&#8204;&#8203;&#8205;&#8205;&#8205;&#8205;&#8205;&#8203;&#8205;&#8205;&#8205;&#8205;&#8205;&#8203;&#8204;&#8204;&#8204;&#8204;&#8204;&#8203;&#8204;&#8205;&#8205;&#8204;&#8205;&#8203;&#8204;&#8204;&#8205;&#8203;&#8205;&#8204;&#8204;&#8204;&#8204;&#8203;&#8205;&#8204;&#8204;&#8204;&#8204;&#8203;&#8204;&#8204;&#8205;&#8205;&#8205;&#8203;&#8204;&#8204;&#8205;&#8204;&#8203;&#8203;&#8204;&#8203;&#8204;&#8204;&#8204;&#8203;&#8204;&#8205;&#8204;&#8204;&#8203;&#8204;&#8204;&#8203;&#8204;&#8203;&#8203;&#8204;&#8204;&#8204;&#8204;&#8203;&#8204;&#8204;&#8205;
```

将这段加密文本进行解密，得到:

>作者是esliehu

这是我哪里做的不对？还是解密丢失了`L`和`z`字符？

**Comment by rover95** [comment]
> 在：http://morse.rovelast.com/
> 
> 比如：前后文本都不设置，只填入加密文本: `作者是LeslieZhu`，点击加密，得到加密文本:
> 
> ```
> &#8204;&#8205;&#8205;&#8204;&#8205;&#8203;&#8204;&#8204;&#8205;&#8203;&#8204;&#8204;&#8204;&#8204;&#8205;&#8203;&#8204;&#8204;&#8205;&#8204;&#8203;&#8204;&#8204;&#8204;&#8204;&#8204;&#8203;&#8205;&#8204;&#8205;&#8204;&#8203;&#8204;&#8205;&#8205;&#8204;&#8205;&#8203;&#8204;&#8204;&#8205;&#8203;&#8205;&#8205;&#8205;&#8204;&#8204;&#8203;&#8205;&#8205;&#8205;&#8205;&#8205;&#8203;&#8205;&#8205;&#8205;&#8205;&#8205;&#8203;&#8204;&#8204;&#8204;&#8204;&#8204;&#8203;&#8204;&#8205;&#8205;&#8204;&#8205;&#8203;&#8204;&#8204;&#8205;&#8203;&#8205;&#8204;&#8204;&#8204;&#8204;&#8203;&#8205;&#8204;&#8204;&#8204;&#8204;&#8203;&#8204;&#8204;&#8205;&#8205;&#8205;&#8203;&#8204;&#8204;&#8205;&#8204;&#8203;&#8203;&#8204;&#8203;&#8204;&#8204;&#8204;&#8203;&#8204;&#8205;&#8204;&#8204;&#8203;&#8204;&#8204;&#8203;&#8204;&#8203;&#8203;&#8204;&#8204;&#8204;&#8204;&#8203;&#8204;&#8204;&#8205;
> ```
> 
> 将这段加密文本进行解密，得到:
> 
> > 作者是esliehu
> 
> 这是我哪里做的不对？还是解密丢失了`L`和`z`字符？

因为是才用摩斯码加密的,摩斯码不区分大小写,所以不支持大写字母, 现在在原来基础上加了Unicode编码可以支持全字符

**Comment by LeslieZhu** [comment]
thx.
